[profile.default]
solc = "0.8.19"
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000

remappings = [
    "forge-std/=lib/forge-std/src/",
]

[profile.ci]
solc = "0.8.19"
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
verbosity = 3

remappings = [
    "forge-std/=lib/forge-std/src/",
]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
